import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { briefRowToBrief, getAllBriefs } from '@/lib/db';
import type { Brief } from '@/lib/types';
import { SITE_URL } from '@/lib/seo';
import { localeAlternates } from '@/lib/i18n-seo';
import CustomCollisionCta from '@/components/CustomCollisionCta';
import BriefsClient from './BriefsClient';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: 'briefsPage' });
  const briefs: Brief[] = getAllBriefs().map(briefRowToBrief);
  const domainCount = new Set(briefs.flatMap((b) => b.domains)).size;
  // Compose a stat-aware description that matches the active locale.
  const description =
    briefs.length > 0
      ? locale === 'fr'
        ? `Explorez les hypothèses de recherche générées par SPORE : ${briefs.length} brief${briefs.length > 1 ? 's' : ''} publié${briefs.length > 1 ? 's' : ''}, couvrant ${domainCount} domaines scientifiques, validés par 5 relecteurs IA.`
        : `Browse the research hypotheses generated by SPORE: ${briefs.length} brief${briefs.length > 1 ? 's' : ''} published, covering ${domainCount} scientific domains, validated by 5 AI reviewers.`
      : t('metaDescription');

  return {
    title: t('metaTitle'),
    description,
    alternates: localeAlternates(locale, '/briefs'),
    openGraph: {
      title: `${t('metaTitle')} | SPORE`,
      description,
      url: `${SITE_URL}/${locale}/briefs`,
      type: 'website',
      locale: locale === 'fr' ? 'fr_FR' : 'en_US',
      images: [
        {
          url: '/og-default.png',
          width: 1200,
          height: 630,
          alt: 'SPORE',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${t('metaTitle')} | SPORE`,
      description,
      images: ['/og-default.png'],
    },
  };
}

export default async function BriefsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations({ locale, namespace: 'briefsPage' });

  const briefs: Brief[] = getAllBriefs().map(briefRowToBrief);
  const allDomains = Array.from(
    new Set(briefs.flatMap((b) => b.domains)),
  ).sort();

  return (
    <div className="mx-auto max-w-7xl px-6 py-16 md:py-24">
      <header className="mb-12 md:mb-16">
        <h1 className="mb-3 font-display text-4xl text-mist-100 md:text-6xl">
          {t('pageTitle')}
        </h1>
        <p className="max-w-2xl text-lg text-mist-400">
          {t('pageIntroBefore')}
          <span className="text-emerald-glow">{t('pageIntroAccent')}</span>
          {t('pageIntroAfter')}
        </p>
      </header>

      <BriefsClient briefs={briefs} allDomains={allDomains} />

      <div className="mt-20">
        <CustomCollisionCta
          headline={t('ctaHeadline')}
          subtext={t('ctaSubtext')}
          cta={t('ctaButton')}
        />
      </div>
    </div>
  );
}
